services:
  # Backend API сервер
  - type: web
    name: evrika-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://evrika-frontend.onrender.com

  # Frontend SvelteKit приложение
  - type: web
    name: evrika-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci --include=dev && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://evrika-backend.onrender.com/api
